"""
Rich-based TUI runner for Countdown solvers.

Provides an interactive Text User Interface (TUI) to run all three solvers
against five pre-loaded examples of increasing difficulty, or custom inputs.
Reads output files from concurrent shell-script execution and displays them
in a comparison view.
"""

import os
import subprocess
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.columns import Columns
from rich.prompt import Prompt

TEMP_DIR = "/tmp/countdown_results"

SOLVERS = [
    ("Python", "python", "Py", "#3572A5"),
    ("Haskell", "haskell", "HS", "#5e5086"),
    ("Prolog", "prolog", "PL", "#74283C"),
]

EXAMPLES = [
    {"name": "Difficulty 1 (Very Easy)", "target": 10, "numbers": [1, 2, 3, 4]},
    {"name": "Difficulty 2 (Easy)", "target": 50, "numbers": [2, 3, 5, 10, 25]},
    {"name": "Difficulty 3 (Medium)", "target": 123, "numbers": [1, 2, 3, 4, 25]},
    {"name": "Difficulty 4 (Hard)", "target": 456, "numbers": [1, 3, 5, 10, 25, 50]},
    {"name": "Difficulty 5 (Very Hard)", "target": 987, "numbers": [1, 2, 3, 4, 75, 100]},
]


def readFile(path: str) -> str:
    """
    Reads a file and returns its contents, or an empty string on error.

    Args:
        path (str): The absolute or relative file path to read.

    Returns:
        str: The full text content of the file, stripped of trailing whitespace.
    """
    try:
        with open(path) as f:
            return f.read().strip()
    except (FileNotFoundError, PermissionError):
        return ""


def parseOutput(text: str) -> dict:
    """
    Parses solver output into structured result data.

    Args:
        text (str): The raw text output generated by a solver execution.

    Returns:
        dict: A dictionary containing extracted keys 'expression', 'value', 'success', and 'raw'.
    """
    result = {
        "expression": "N/A",
        "value": "N/A",
        "success": False,
        "raw": text or "No output captured.",
    }

    for line in text.splitlines():
        if line.startswith("Expression:"):
            result["expression"] = line.replace("Expression:", "").strip()  # Extracts the calculated expression string.
            result["success"] = True  # Marks the result as successful since an expression was found.
        elif line.startswith("Value:"):
            result["value"] = line.replace("Value:", "").strip()  # Extracts the evaluated result value.
        elif "No solution" in line:
            result["success"] = False  # Marks the result as unsuccessful due to failure text.

    return result


def buildSolverPanel(name: str, output: dict, time_str: str, color: str) -> Panel:
    """
    Constructs a Rich Panel for displaying a single solver's result.

    Args:
        name (str): The display name of the solver.
        output (dict): The parsed output data from the solver.
        time_str (str): The recorded execution time as a string.
        color (str): The theme color string used for status indicators.

    Returns:
        Panel: A Rich framework Panel object configured with the provided results.
    """
    if output["success"]:
        status = Text("SOLVED", style=f"bold {color}")
    else:
        status = Text("NO SOLUTION", style="bold red")

    content = Text.assemble(
        ("Expression: ", "bold"),
        (output["expression"], "cyan" if output["success"] else "dim"),
        "\n",
        ("Value: ", "bold"),
        (output["value"], "cyan" if output["success"] else "dim"),
        "\n\n",
        ("Time: ", "bold"),
        (f"{time_str}s", "yellow"),
        "\n",
        ("Status: ", "bold"),
        status,
    )

    return Panel(content, title=f"[bold]{name}[/bold]", border_style=color)


def buildBenchmarkTable(solver_data: list) -> Table:
    """
    Generates a comparison table summarizing execution data for all solvers.

    Args:
        solver_data (list): A list containing tuples of solver results.

    Returns:
        Table: A Rich framework Table object containing the benchmark comparison info.
    """
    table = Table(
        title="Benchmark Comparison",
        show_header=True,
        header_style="bold magenta",
        expand=True,
    )
    table.add_column("Solver", justify="center", style="bold cyan")
    table.add_column("Time", justify="center", style="yellow")
    table.add_column("Result", justify="center")
    table.add_column("Match", justify="center")

    reference_value = None  # Stores the first valid result for consensus comparison.
    for name, output, time_str, color in solver_data:
        if output["success"]:
            reference_value = output["value"]
            break  # Stops searching if valid reference is obtained.

    for name, output, time_str, color in solver_data:
        result = "PASS" if output["success"] else "FAIL"
        style = "green" if output["success"] else "red"

        if output["success"] and reference_value:
            matches = output["value"] == reference_value
            match_str = "\u2714 YES" if matches else "\u2718 DIFFERS" 
            match_style = "green" if matches else "red"
        else:
            match_str = "N/A"
            match_style = "dim"

        table.add_row(
            name,
            f"{time_str}s",
            f"[{style}]{result}[/{style}]",
            f"[{match_style}]{match_str}[/{match_style}]",
        )

    return table


def findFastest(solver_data: list) -> str:
    """
    Identifies the solver demonstrating the lowest execution time.

    Args:
        solver_data (list): A list containing solver summary tuples.

    Returns:
        str: The name of the solver exhibiting the fastest execution, or 'N/A'.
    """
    times = []
    for name, _, time_str, _ in solver_data:
        try:
            t = float(time_str)
            times.append((name, t))
        except ValueError:
            pass  # Ignore invalid timing formats.

    if times:
        return min(times, key=lambda x: x[1])[0]  # Returns the entry with the minimal time index.
    return "N/A"


def runSolvers(target: int, numbers: list, console: Console) -> None:
    """
    Invokes the shell script to run all solvers simultaneously.

    Args:
        target (int): The target total to achieve.
        numbers (list): The integers allowed in the expression construction.
        console (Console): The Rich console framework instance.

    Returns:
        None
    """
    script_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "run_all.sh")  # Resolve path
    args = [script_path, str(target)] + [str(n) for n in numbers]
    
    with console.status("[bold green]Running all 3 solvers... This might take a while.[/bold green]") as status:
        subprocess.run(args, capture_output=True, text=True)  


def displayResults(console: Console) -> None:
    """
    Collects outputs from individual runner components and manages TUI drawing.

    Args:
        console (Console): The framework console context responsible for drawing.

    Returns:
        None
    """
    solver_data = []
    for name, lang_hint, emoji, color in SOLVERS:
        output_text = readFile(os.path.join(TEMP_DIR, f"{lang_hint}_output.txt"))
        time_str = readFile(os.path.join(TEMP_DIR, f"{lang_hint}_time.txt"))
        time_str = time_str if time_str else "N/A"

        output = parseOutput(output_text)
        solver_data.append((name, output, time_str, color))

    panels = [
        buildSolverPanel(name, output, time_str, color)
        for name, output, time_str, color in solver_data
    ]

    console.print()
    console.rule("[bold green]Solver Results[/bold green]")
    console.print()

    columns = Columns(panels, equal=True, expand=True)
    console.print(columns)
    console.print()

    console.print(buildBenchmarkTable(solver_data))
    console.print()

    fastest = findFastest(solver_data)
    console.print(
        f"[bold]Fastest Solver:[/bold] [green]{fastest}[/green] "
        if fastest != "N/A"
        else "[bold]Fastest Solver:[/bold] [yellow]Unable to determine[/yellow]"
    )

    values = [
        output["value"]
        for _, output, _, _ in solver_data
        if output["success"]
    ]
    if len(set(values)) <= 1 and len(values) > 0:
        console.print("[bold green]All solutions match: PASS[/bold green]")
    elif len(values) > 1:
        console.print("[bold red]Solution values differ: FAIL[/bold red]")
    else:
        console.print("[bold yellow]No successful solutions to compare[/bold yellow]")


def main() -> None:
    """
    Initializes application loop, handles menus, and triggers solver flows.

    Args:
        None

    Returns:
        None
    """
    console = Console()
    
    while True:
        console.clear()
        console.rule("[bold green]Countdown Numbers Game - TUI[/bold green]")
        
        table = Table(title="Preloaded Examples", show_header=True, header_style="bold magenta")
        table.add_column("Option", style="cyan", justify="right")
        table.add_column("Difficulty", style="green")
        table.add_column("Target", style="bold yellow")
        table.add_column("Numbers")
        
        for i, ex in enumerate(EXAMPLES):
            num_str = ", ".join(map(str, ex["numbers"]))
            table.add_row(str(i+1), ex["name"], str(ex["target"]), num_str)
            
        console.print(table)
        console.print("6. [bold cyan]Custom[/bold cyan] - Enter your own target and numbers")
        console.print("0. [bold red]Exit[/bold red]")
        
        console.print()
        choice = Prompt.ask("Select an option", choices=["0", "1", "2", "3", "4", "5", "6"])
        
        if choice == "0":
            break  # Kill the application.
        
        if choice == "6":
            target_str = Prompt.ask("Enter the target number")
            numbers_str = Prompt.ask("Enter the available numbers separated by spaces")
            try:
                target = int(target_str)
                numbers = [int(n) for n in numbers_str.split()]
            except ValueError:
                console.print("[bold red]Invalid input![/bold red]")
                Prompt.ask("Press Enter to continue")
                continue  # Bypasses execution back to menu.
        else:
            idx = int(choice) - 1
            target = EXAMPLES[idx]["target"]
            numbers = EXAMPLES[idx]["numbers"]
            
        runSolvers(target, numbers, console)
        displayResults(console)
        
        console.print()
        Prompt.ask("Press Enter to return to the menu")


if __name__ == "__main__":
    main()
